CREATE TABLE `approxes` (
  `id` int(11) NOT NULL auto_increment,
  `exactstr` varchar(255) default NULL,
  `soundexstr` varchar(255) default NULL,
  `classstr` varchar(127) default NULL,
  `attribstr` varchar(63) default NULL,
  `targetrow` int(11) default NULL,
  `flags` int(11) default NULL,
  PRIMARY KEY  (`id`),
  KEY `exactstr` (`exactstr`),
  KEY `classstr` (`classstr`),
  KEY `attribstr` (`attribstr`),
  KEY `targetrow` (`targetrow`)
) TYPE=MyISAM;

CREATE TABLE `diseases` (
  `id` int(11) NOT NULL auto_increment,
  `discat` int(11) default NULL,
  `flags` int(11) default '0',
  `name` varchar(32) NOT NULL default '',
  `numcases` int(11) NOT NULL default '1',
  `reliefcon` varchar(32) NOT NULL default '',
  `when` timestamp(14) NOT NULL,
  `cuid` int(11) default NULL,
  `muid` int(11) default NULL,
  `lastchange` timestamp(14) NOT NULL default '00000000000000',
  `emails` varchar(255) NOT NULL default '',
  `loc` varchar(32) NOT NULL default 'G-U',
  `notes` text,
  PRIMARY KEY  (`id`),
  KEY `discat` (`discat`),
  KEY `flags` (`flags`),
  KEY `name` (`name`),
  KEY `numcases` (`numcases`),
  KEY `reliefcon` (`reliefcon`),
  KEY `when` (`when`),
  KEY `cuid` (`cuid`),
  KEY `muid` (`muid`),
  KEY `lastchange` (`lastchange`),
  KEY `emails` (`emails`)
) TYPE=MyISAM;

CREATE TABLE `locations` (
  `id` int(11) NOT NULL auto_increment,
  `loccode` varchar(32) NOT NULL default '',
  `name` varchar(32) NOT NULL default '',
  `prompt` varchar(32) default NULL,
  `flags` int(11) default '0',
  `fullcode` varchar(255) NOT NULL default '',
  `parent` int(11) default NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `fullcode` (`fullcode`),
  KEY `name` (`name`),
  KEY `loccode` (`loccode`),
  KEY `flags` (`flags`),
  KEY `parent` (`parent`)
) TYPE=MyISAM;

CREATE TABLE `people` (
  `id` int(11) NOT NULL auto_increment,
  `name` varchar(64) default NULL,
  `age` int(11) default NULL,
  `sex` int(11) default NULL,
  `height` varchar(16) default NULL,
  `weight` varchar(16) default NULL,
  `haircolor` varchar(16) default NULL,
  `eyecolor` varchar(16) default NULL,
  `homeaddr` varchar(255) default NULL,
  `famconame` varchar(64) default NULL,
  `famcophone` varchar(64) default NULL,
  `famcorel` varchar(64) default NULL,
  `famemail` varchar(64) default NULL,
  `famnum` int(11) default NULL,
  `relconame` varchar(64) default NULL,
  `relcophone` varchar(64) default NULL,
  `relcoorg` varchar(64) default NULL,
  `speclostplace` text,
  `lostloc` varchar(64) default 'G-U',
  `foundloc` varchar(64) default 'G-U',
  `stayingloc` varchar(64) default 'G-U',
  `status` int(11) default NULL,
  `lastupdate` timestamp(14) NOT NULL,
  `notes` text,
  `emails` text,
  `mednotes` text,
  `hospital` varchar(128) default NULL,
  `origcode` char(2) default NULL,
  `cuid` int(11) default NULL,
  `createtime` timestamp(14) NOT NULL default '00000000000000',
  `muid` int(11) default NULL,
  `modtime` timestamp(14) NOT NULL default '00000000000000',
  PRIMARY KEY  (`id`),
  KEY `name` (`name`),
  KEY `notes` (`notes`(255))
) TYPE=MyISAM;

CREATE TABLE `phonenums` (
  `id` int(11) NOT NULL auto_increment,
  `name` varchar(64) default NULL,
  `dialcode` varchar(64) default NULL,
  `notes` text,
  `loc` varchar(64) default 'G-U',
  `flags` int(11) NOT NULL default '0',
  `cat` int(11) default NULL,
  `uid` int(11) default NULL,
  PRIMARY KEY  (`id`),
  KEY `name` (`name`),
  KEY `notes` (`notes`(255))
) TYPE=MyISAM;

CREATE TABLE `supplies` (
  `id` int(11) NOT NULL auto_increment,
  `loc` varchar(32) NOT NULL default '',
  `supcat` int(11) default NULL,
  `flags` int(11) default '0',
  `name` varchar(32) NOT NULL default '',
  `quantity` varchar(32) NOT NULL default '',
  `origcode` char(2) NOT NULL default '',
  `status` int(11) default '0',
  `fromcon` varchar(255) default NULL,
  `tocon` varchar(255) default NULL,
  `fromloc` varchar(32) NOT NULL default '',
  `toloc` varchar(32) NOT NULL default '',
  `notes` varchar(255) default NULL,
  `fromwho` varchar(255) default NULL,
  `cuid` int(11) default NULL,
  `muid` int(11) default NULL,
  `lastchange` timestamp(14) NOT NULL,
  `emails` varchar(255) NOT NULL default '',
  PRIMARY KEY  (`id`),
  KEY `name` (`name`),
  KEY `supcat` (`supcat`),
  KEY `flags` (`flags`),
  KEY `fromloc` (`fromloc`),
  KEY `toloc` (`toloc`),
  KEY `notes` (`notes`),
  KEY `fromwho` (`fromwho`)
) TYPE=MyISAM;

CREATE TABLE `users` (
  `id` int(11) NOT NULL auto_increment,
  `login` varchar(80) default NULL,
  `password` varchar(40) default NULL,
  `flags` int(11) default '0',
  `email` varchar(64) default NULL,
  `writep` varchar(255) NOT NULL default '',
  `readp` varchar(255) NOT NULL default '',
  `managep` varchar(255) NOT NULL default '',
  `adminp` varchar(255) NOT NULL default '',
  `veremail` varchar(255) NOT NULL default '',
  PRIMARY KEY  (`id`)
) TYPE=MyISAM;

CREATE TABLE `volunteers` (
  `id` int(11) NOT NULL auto_increment,
  `name` varchar(64) default NULL,
  `age` int(11) default NULL,
  `sex` int(11) default NULL,
  `email` varchar(64) default NULL,
  `phone` varchar(64) default NULL,
  `curloc` varchar(64) default 'G-U',
  `targetloc` varchar(64) default 'G-U',
  `targetstart` timestamp(14) NOT NULL,
  `targetend` timestamp(14) NOT NULL default '00000000000000',
  `targetagency` varchar(255) default NULL,
  `flags` int(11) default NULL,
  `skillcat` int(11) default NULL,
  `skilldesc` varchar(255) default NULL,
  `origcode` char(2) default NULL,
  `notes` text,
  `cuid` int(11) NOT NULL default '0',
  `muid` int(11) NOT NULL default '0',
  `canpay` int(11) NOT NULL default '0',
  PRIMARY KEY  (`id`),
  KEY `name` (`name`),
  KEY `notes` (`notes`(255)),
  KEY `phone` (`phone`),
  KEY `curloc` (`curloc`),
  KEY `targetloc` (`targetloc`),
  KEY `targetagency` (`targetagency`),
  KEY `flags` (`flags`),
  KEY `skillcat` (`skillcat`),
  KEY `skilldesc` (`skilldesc`)
) TYPE=MyISAM;

